<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="testAll"
           tests="5"
           failures="4"
           errors="0"
           skipped="0"
           time="223.882">
  <properties />
            <testcase name="loginConfim2" time="44.173" classname="com.yiibai.primera.testng.cases.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="帐号密码对的情况登录 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
  
报错信息: expected [true] but found [false].
报错方法名:loginConfim2(
报错类:LoginTest
报错行号:84)
  com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:84)
  com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:85)
]]>
      </failure>

          </testcase>
            <testcase name="loginErrorNum" time="45.731" classname="com.yiibai.primera.testng.cases.LoginTest">
                <failure type="java.lang.Throwable"
                  message="(null)"
              >
<![CDATA[java.lang.Throwable
  
报错信息: expected [true] but found [false].
报错方法名:loginErrorNum(
报错类:LoginTest
报错行号:42)
  com.yiibai.primera.testng.cases.LoginTest.loginErrorNum(LoginTest.java:42)
]]>
      </failure>

          </testcase>
            <testcase name="loginChinese" time="45.654" classname="com.yiibai.primera.testng.cases.LoginTest">
                <failure type="java.lang.Throwable"
                  message="(null)"
              >
<![CDATA[java.lang.Throwable
  
报错信息: expected [true] but found [false].
报错方法名:loginChinese(
报错类:LoginTest
报错行号:53)
  com.yiibai.primera.testng.cases.LoginTest.loginChinese(LoginTest.java:53)
]]>
      </failure>

          </testcase>
            <testcase name="loginErrorUser" time="48.542" classname="com.yiibai.primera.testng.cases.LoginTest">
                <failure type="java.lang.Throwable"
                  message="(null)"
              >
<![CDATA[java.lang.Throwable
  
报错信息: expected [true] but found [false].
报错方法名:loginErrorUser(
报错类:LoginTest
报错行号:32)
  com.yiibai.primera.testng.cases.LoginTest.loginErrorUser(LoginTest.java:32)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="loginConfim" time="39.782" classname="com.yiibai.primera.testng.cases.LoginTest" />
      
</testsuite>
