<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="57.035">
  <properties />
            <testcase name="loginConfim" time="4.654" classname="com.yiibai.primera.testng.cases.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="帐号密码对的情况登录 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  com.yiibai.primera.testng.cases.LoginTest.loginConfim(LoginTest.java:76)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="loginChinese" time="4.515" classname="com.yiibai.primera.testng.cases.LoginTest" />
                <testcase name="loginEmpty" time="4.218" classname="com.yiibai.primera.testng.cases.LoginTest" />
                <testcase name="loginErrorUser" time="39.372" classname="com.yiibai.primera.testng.cases.LoginTest" />
                <testcase name="loginErrorNum" time="4.276" classname="com.yiibai.primera.testng.cases.LoginTest" />
      
</testsuite>
