<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="58818" started-at="2017-08-30T09:21:32Z" finished-at="2017-08-30T09:22:31Z">
    <groups>
    </groups>
    <test name="Login" duration-ms="58818" started-at="2017-08-30T09:21:32Z" finished-at="2017-08-30T09:22:31Z">
      <class name="com.yiibai.primera.testng.cases.LoginTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="beforeSuite" is-config="true" duration-ms="65540" started-at="2017-08-30T17:20:27Z" finished-at="2017-08-30T17:21:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="initDriver" is-config="true" duration-ms="35" started-at="2017-08-30T17:21:32Z" finished-at="2017-08-30T17:21:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="loginErrorUser()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="loginErrorUser" duration-ms="39372" started-at="2017-08-30T17:21:32Z" finished-at="2017-08-30T17:22:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorUser -->
        <test-method status="PASS" signature="loginErrorNum()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="loginErrorNum" duration-ms="4276" started-at="2017-08-30T17:22:12Z" finished-at="2017-08-30T17:22:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorNum -->
        <test-method status="PASS" signature="loginChinese()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="loginChinese" duration-ms="4515" started-at="2017-08-30T17:22:16Z" finished-at="2017-08-30T17:22:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginChinese -->
        <test-method status="PASS" signature="loginEmpty()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="loginEmpty" duration-ms="4218" started-at="2017-08-30T17:22:21Z" finished-at="2017-08-30T17:22:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginEmpty -->
        <test-method status="FAIL" signature="loginConfim()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="loginConfim" duration-ms="4654" started-at="2017-08-30T17:22:25Z" finished-at="2017-08-30T17:22:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[帐号密码对的情况登录 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim(LoginTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginConfim -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-08-30T17:22:29Z" finished-at="2017-08-30T17:22:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.yiibai.primera.testng.cases.LoginTest@6737fd8f]" name="afterTest" is-config="true" duration-ms="1733" started-at="2017-08-30T17:22:29Z" finished-at="2017-08-30T17:22:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.yiibai.primera.testng.cases.LoginTest -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
