<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cpj" name="com.yiibai.primera.testng.cases.LoginTest" tests="5" failures="3" timestamp="22 Sep 2017 04:24:50 GMT" time="202.404" errors="1">
  <testcase name="loginConfim2" time="36.185" classname="com.yiibai.primera.testng.cases.LoginTest"/>
  <testcase name="loginConfim" time="41.809" classname="com.yiibai.primera.testng.cases.LoginTest">
    <error type="java.lang.AssertionError" message="帐号密码对的情况登录 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
	at 
报错信息: expected [true] but found [false].
报错方法名:loginConfim(
报错类:LoginTest
报错行号:73)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim(LoginTest.java:73)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim(LoginTest.java:74)
]]>
    </error>
  </testcase> <!-- loginConfim -->
  <testcase name="loginErrorNum" time="38.577" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorNum(
报错类:LoginTest
报错行号:41)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorNum(LoginTest.java:41)
]]>
    </failure>
  </testcase> <!-- loginErrorNum -->
  <testcase name="loginChinese" time="38.870" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginChinese(
报错类:LoginTest
报错行号:52)
	at com.yiibai.primera.testng.cases.LoginTest.loginChinese(LoginTest.java:52)
]]>
    </failure>
  </testcase> <!-- loginChinese -->
  <testcase name="loginErrorUser" time="46.963" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorUser(
报错类:LoginTest
报错行号:31)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorUser(LoginTest.java:31)
]]>
    </failure>
  </testcase> <!-- loginErrorUser -->
</testsuite> <!-- com.yiibai.primera.testng.cases.LoginTest -->
