<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cpj" name="com.yiibai.primera.testng.cases.LoginTest" tests="5" failures="3" timestamp="27 Sep 2017 03:23:21 GMT" time="224.002" errors="1">
  <testcase name="loginChinese" time="45.723" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginChinese(
报错类:LoginTest
报错行号:53)
	at com.yiibai.primera.testng.cases.LoginTest.loginChinese(LoginTest.java:53)
]]>
    </failure>
  </testcase> <!-- loginChinese -->
  <testcase name="loginConfim2" time="44.187" classname="com.yiibai.primera.testng.cases.LoginTest">
    <error type="java.lang.AssertionError" message="帐号密码对的情况登录 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
	at 
报错信息: expected [true] but found [false].
报错方法名:loginConfim2(
报错类:LoginTest
报错行号:84)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:84)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:85)
]]>
    </error>
  </testcase> <!-- loginConfim2 -->
  <testcase name="loginErrorUser" time="48.556" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorUser(
报错类:LoginTest
报错行号:32)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorUser(LoginTest.java:32)
]]>
    </failure>
  </testcase> <!-- loginErrorUser -->
  <testcase name="loginConfim" time="39.793" classname="com.yiibai.primera.testng.cases.LoginTest"/>
  <testcase name="loginErrorNum" time="45.743" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorNum(
报错类:LoginTest
报错行号:42)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorNum(LoginTest.java:42)
]]>
    </failure>
  </testcase> <!-- loginErrorNum -->
</testsuite> <!-- com.yiibai.primera.testng.cases.LoginTest -->
